### ISSUE TITLE
Permission denied on Kubernetes

### ISSUE THREAD

**Issue by dmarkey** [DataDog/uwsgi-dogstatsd#19]
On EKS, I'm getting this error in the uwsgi logs.

Anyone seen it before and how to remedy?

dogstatsd_send_metric()/sendto(): Permission denied [/uwsgi-dogstatsd/plugin.c line 173]

Thanks!

David

**Comment by dmarkey** [comment]
Sorry this was PEBCAK. Was not configured correctly

**Comment by AlecTroemel** [comment]
I'm getting the same error in k8s, @dmarkey you mind sharing what your config error was (in case I've made the same mistake)?

**Comment by dmarkey** [comment]
As this project seems kind of abandoned we're switching to https://github.com/timonwong/uwsgi_exporter + 
```
      annotations:
        ad.datadoghq.com/uwsgi-exporter.check_names: '["openmetrics"]'
        ad.datadoghq.com/uwsgi-exporter.init_configs: '[{}]'
        ad.datadoghq.com/uwsgi-exporter.instances: '[{"prometheus_url": "http://%%host%%:9117/metrics","namespace":
          "uwsgi_dd","metrics": ["*"]}]'
```
